dataset:
  name: ImageNet
  train_augmentation:
    resize_shorter_side_range: [256, 480]
    crop_size: 224
    random_horizontal_flip: true
    subtract_mean: true
    color_augmentation: true  # Color jittering
  test_augmentation:
    mode: 10-crop
    fully_convolutional_eval: true
    multi_scale_eval: [224, 256, 384, 480, 640]