# ResNet configuration for ImageNet training and evaluation
dataset:
  data_dir: "/kaggle/input/tiny-imagenett/tiny-imagenet-200"
  batch_size: 256

model:
  name: ResNet
  input_shape: [64, 64, 3]
  num_classes: 200
  batch_norm:
    enabled: true
    position: after_conv_before_activation
  weight_init: HeNormal  # He initialization for ReLU activations
  dropout: false

seed: 42

training:
  optimizer: 
   name: SGD
  learning_rate:
    initial: 0.01
    schedule:
      type: plateau
      factor: 0.1
  weight_decay: 0.0001
  momentum: 0.9
  epochs: 50 # Total number of iterations for training
  pretrained: false  # train from scratch
  label_smoothing: 0.1  
