# ResNet configuration for ImageNet training and evaluation

dataset:
  name: ImageNet
  train_augmentation:
    resize_shorter_side_range: [256, 480]
    crop_size: 224
    random_horizontal_flip: true
    subtract_mean: true
    color_augmentation: true  # Color jittering
  test_augmentation:
    mode: 10-crop
    fully_convolutional_eval: true
    multi_scale_eval: [224, 256, 384, 480, 640]

model:
  name: ResNet
  input_shape: [64, 64, 3]
  num_classes: 200
  batch_norm:
    enabled: true
    position: after_conv_before_activation
  weight_init: HeNormal  # He initialization for ReLU activations
  dropout: false

training:
  optimizer: SGD
  batch_size: 256
  learning_rate:
    initial: 0.1
    schedule:
      type: plateau
      factor: 0.1
  weight_decay: 0.0001
  momentum: 0.9
  max_iterations: 600000 # Total number of iterations for training
  pretrained: false  # train from scratch

testing:
  strategy: standard_and_multi_scale