# ResNet configuration for ImageNet training and evaluation
model:
  name: ResNet
  input_shape: [224, 224, 3]
  num_classes: 200
  batch_norm:
    enabled: true
    position: after_conv_before_activation
  weight_init: HeNormal  # He initialization for ReLU activations
  dropout: false

training:
  optimizer: SGD
  batch_size: 256
  learning_rate:
    initial: 0.1
    schedule:
      type: plateau
      factor: 0.1
  weight_decay: 0.0001
  momentum: 0.9
  epochs: 100 # Total number of iterations for training
  pretrained: false  # train from scratch
