# Vision Transformer (ViT) configurations for training
seed: 42

dataset:
  data_dir: "/content/drive/MyDrive/datasets/tiny-imagenet-200"
  batch_size: 1024

# Base configuration for training and evaluation
model:
  name: VisionTransformer
  input_shape: [224, 224, 3]
  num_classes: 200
  patch_size: 16
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  mlp_dim: 3072
  dropout: 0.1
  attention_dropout: 0.0
  classifier: token
  pretrained: false # train from scratch

training:
  optimizer: Adam
  adam_betas: [0.9, 0.999]
  learning_rate:
    initial: 0.1
    schedule:
      type: plateau
      factor: 0.1
  weight_decay: 0.1
  epochs: 100 # Total number of epochs for training
  gradient_clipping: null
  label_smoothing: 0.1