name: Create & Push Docker Image to Docker Hub and Deploy API to Hugging Face

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_BASE: b3rian/image-classifier-api
  BRANCH_NAME: deploy-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the deploy-api branch code
    - name: Checkout deploy-api branch
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH_NAME }}

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10