name: Create & Push Docker Image to Docker Hub and Deploy Streamlit UI to Hugging Face & Render

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_BASE: b3rian/image-classifier-ui
  BRANCH_NAME: deploy-streamlit-hugging-face

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the deploy-streamlit branch code
    - name: Checkout deploy-api branch
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH_NAME }}

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    # Step 3: Install Python dependencies
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub